apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: smartlog
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.16.0
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: node
    count: 2
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 2Gi
              cpu: 1
            requests:
              memory: 2Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
          - name: cluster.initial_master_nodes
            value: "smartlog-es-node-0,smartlog-es-node-1"
        nodeSelector:
          app: elasticsearch
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi