apiVersion: v1
kind: Service
metadata:
  name: simon-service
spec:
  selector:
    app: simon
  ports:
    - port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-simon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app.log
      pos_file app.pos
      time_format %Y-%m-%dT%H:%M:%S
      tag simon.*
      <parse>
        @type none
      </parse>
      
    </source>

    <match **>
      @type elasticsearch
      @id out_es
      @log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      path "#{ENV['FLUENT_ELASTICSEARCH_PATH']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      user "#{ENV['FLUENT_ELASTICSEARCH_USER'] || use_default}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD'] || use_default}"
      reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'false'}"
      reconnect_on_error "#{ENV['FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR'] || 'true'}"
      reload_on_failure "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_ON_FAILURE'] || 'true'}"
      log_es_400_reason "#{ENV['FLUENT_ELASTICSEARCH_LOG_ES_400_REASON'] || 'false'}"
      logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'app6'}"
      logstash_dateformat "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_DATEFORMAT'] || '%Y.%m.%d'}"
      logstash_format "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT'] || 'true'}"
      index_name "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME'] || 'app6'}"
      type_name "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_TYPE_NAME'] || 'fluentd'}"
      include_timestamp "#{ENV['FLUENT_ELASTICSEARCH_INCLUDE_TIMESTAMP'] || 'false'}"
      template_name "#{ENV['FLUENT_ELASTICSEARCH_TEMPLATE_NAME'] || use_nil}"
      template_file "#{ENV['FLUENT_ELASTICSEARCH_TEMPLATE_FILE'] || use_nil}"
      template_overwrite "#{ENV['FLUENT_ELASTICSEARCH_TEMPLATE_OVERWRITE'] || use_default}"
      sniffer_class_name "#{ENV['FLUENT_SNIFFER_CLASS_NAME'] || 'Fluent::Plugin::ElasticsearchSimpleSniffer'}"
      request_timeout "#{ENV['FLUENT_ELASTICSEARCH_REQUEST_TIMEOUT'] || '5s'}"
    </match>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon
spec:
  selector:
    matchLabels:
      app: simon
  replicas: 2
  template:
    metadata:
      labels:
        app: simon
    spec:
      containers:
        - name: log-simon
          image: congcuong97/simon:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: simondata
              mountPath: /var/log
              subPath: app.log
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "k8s-default-smartlog-c4b7613c60-351638399.ap-southeast-1.elb.amazonaws.com"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "80"
            - name:  FLUENT_ELASTICSEARCH_USER
              value: "elastic"
            - name:  FLUENT_ELASTICSEARCH_PASSWORD
              value: "NL53dQh9X488Vy02iX54ZgjE"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENT_UID
              value: "0"
          volumeMounts:
            - name: simondata
              mountPath: /var/log
              subPath: app.log
            - name: fluentd-config
              mountPath: /fluentd/etc
      volumes:
        - name: simondata
          persistentVolumeClaim:
            claimName: pvc-simon
        - name: fluentd-config
          configMap:
            name: fluentd-configmap