apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-elastic
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Delete